import { Schema } from 'effect';

import { Ulid } from '../identifiers.js';

export const AuditActions = [
  'bank.ledger-posted',
  'bank.ledger-reversed',
  'invoice.credited',
  'invoice.refund-recorded',
  'invoice.refund-cancelled',
  'team.invited',
  'team.invitation-cancelled',
  'team.joined',
  'team.member-updated',
  'administrator.bootstrapped',
  'api.token-created',
  'api.token-revoked',
  'api.token-used',
  'authentication.login-succeeded',
  'email.draft-saved',
  'email.template-saved',
  'email.template-archived',
  'email.reminder-scheduled',
  'email.reminder-rejected',
  'email.reminder-cancelled',
  'email.reminder-processed',
  'email.draft-archived',
  'authentication.passkey-added',
  'authentication.passkey-removed',
  'authentication.passkey-login',
  'authentication.logout',
  'authentication.password-changed',
  'authentication.refresh-replay-detected',
  'authentication.sessions-revoked',
  'authentication.session-revoked',
  'client.access-created',
  'client.access-replaced',
  'client.access-revoked',
  'client.archived',
  'client.created',
  'client.reactivated',
  'client.updated',
  'supplier.archived',
  'supplier.created',
  'supplier.reactivated',
  'supplier-invoice.created',
  'supplier-invoice.updated',
  'supplier-invoice.confirmed',
  'supplier-invoice.approved',
  'supplier-invoice.cancelled',
  'supplier-invoice.analysis-settings-updated',
  'supplier-invoice.analysis-submitted',
  'supplier.updated',
  'catalog.created',
  'catalog.updated',
  'document.rendered',
  'invoice.created',
  'invoice.issued',
  'invoice.marked-paid',
  'invoice.payment-recorded',
  'invoice.payment-cancelled',
  'invoice.revised',
  'invoice.voided',
  'issuer.updated',
  'company.settings-updated',
  'company.accounting-initialized',
  'role.created',
  'role.updated',
  'role.deleted',
  'integration.requested',
  'integration.processed',
  'bank.imported',
  'bank.matched',
  'bank.unmatched',
  'quote.accepted',
  'quote.cancelled',
  'quote.condition-preset-created',
  'quote.condition-preset-deleted',
  'quote.condition-preset-updated',
  'quote.created',
  'quote.expired',
  'quote.revised',
  'quote.sent',
  'quote.link-replaced',
] as const;
export const AuditAction = Schema.Literals(AuditActions);
export type AuditAction = typeof AuditAction.Type;

export const AuditResourceType = Schema.String.check(
  Schema.isPattern(/^[a-z]+(?:-[a-z]+)*$/),
  Schema.isMaxLength(40),
);
export type AuditResourceType = typeof AuditResourceType.Type;

export const AuditMetadata = Schema.Record(
  Schema.String.check(Schema.isPattern(/^[a-z][a-zA-Z0-9]*$/), Schema.isMaxLength(40)),
  Schema.String.check(Schema.isMaxLength(500)),
);
export type AuditMetadata = typeof AuditMetadata.Type;

export const AuditEvent = Schema.Struct({
  id: Ulid,
  action: AuditAction,
  actorUserId: Schema.NullOr(Ulid),
  resourceType: AuditResourceType,
  resourceId: Schema.String.check(Schema.isPattern(/\S/), Schema.isMaxLength(160)),
  requestId: Schema.NullOr(Schema.String.check(Schema.isUUID(4))),
  traceId: Schema.NullOr(Schema.String.check(Schema.isPattern(/^[a-f0-9]{32}$/))),
  spanId: Schema.NullOr(Schema.String.check(Schema.isPattern(/^[a-f0-9]{16}$/))),
  occurredAt: Schema.String.check(
    Schema.isPattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/),
  ),
  metadata: AuditMetadata,
});
export type AuditEvent = typeof AuditEvent.Type;
