import { Schema } from 'effect';

export const PermissionCode = Schema.Literals([
  'client.read',
  'client.create',
  'client.update',
  'client.archive',
  'client.access.create',
  'quote.read',
  'quote.create',
  'quote.update',
  'quote.delete',
  'quote.send',
  'quote.sign',
  'order.read',
  'order.create',
  'order.update',
  'invoice.read',
  'invoice.create',
  'invoice.update',
  'invoice.issue',
  'invoice.send',
  'invoice.mark-paid',
  'invoice.void',
  'template.read',
  'template.select',
  'document.render',
  'document.download',
  'user.read',
  'user.create',
  'user.update',
  'session.manage',
  'integration-token.manage',
  'audit.read',
]);
export type PermissionCode = typeof PermissionCode.Type;

export const IntegrationPermissionCodes = [
  'client.read',
  'client.create',
  'client.update',
  'client.archive',
  'quote.read',
  'quote.create',
  'quote.update',
  'quote.delete',
  'quote.send',
  'order.read',
  'invoice.read',
  'invoice.create',
  'invoice.update',
  'invoice.issue',
  'invoice.mark-paid',
  'invoice.void',
  'document.download',
] as const;
export const IntegrationPermissionCode = Schema.Literals(IntegrationPermissionCodes);
export type IntegrationPermissionCode = typeof IntegrationPermissionCode.Type;
