export type ReferenceGroup =
  | 'actions'
  | 'feedback'
  | 'fields'
  | 'data'
  | 'navigation'
  | 'presentation'
  | 'compositions';
export interface ReferenceEntry {
  readonly id: string;
  readonly name: string;
  readonly group: ReferenceGroup;
  readonly selectors: string;
  readonly source: string;
  readonly variants: number;
}

// Le nombre désigne les exemples fixes de la galerie, pas toutes les combinaisons de propriétés.
export const referenceCatalog: readonly ReferenceEntry[] = [
  {
    id: 'button',
    name: 'Button',
    group: 'actions',
    selectors: 'button[appButton]',
    source: 'button/button.ts',
    variants: 10,
  },
  {
    id: 'link-button',
    name: 'LinkButton',
    group: 'actions',
    selectors: 'a[appLinkButton]',
    source: 'button/button.ts',
    variants: 9,
  },
  {
    id: 'action-menu',
    name: 'ActionMenu',
    group: 'actions',
    selectors: 'app-action-menu',
    source: 'action-menu/action-menu.ts',
    variants: 10,
  },
  {
    id: 'split-action',
    name: 'SplitAction',
    group: 'actions',
    selectors: 'app-split-action',
    source: 'split-action/split-action.ts',
    variants: 10,
  },
  {
    id: 'icon-toolbar',
    name: 'IconToolbar',
    group: 'actions',
    selectors: 'app-icon-toolbar',
    source: 'icon-toolbar/icon-toolbar.ts',
    variants: 2,
  },
  {
    id: 'copy-field',
    name: 'CopyField',
    group: 'actions',
    selectors: 'app-copy-field',
    source: 'copy-field/copy-field.ts',
    variants: 3,
  },
  {
    id: 'anchor-link',
    name: 'AnchorLink',
    group: 'actions',
    selectors: 'app-anchor-link',
    source: 'anchor-link/anchor-link.ts',
    variants: 1,
  },
  {
    id: 'badge',
    name: 'Badge',
    group: 'feedback',
    selectors: 'span[appBadge]',
    source: 'badge/badge.ts',
    variants: 4,
  },
  {
    id: 'notice',
    name: 'Notice',
    group: 'feedback',
    selectors: 'p[appNotice], div[appNotice]',
    source: 'notice/notice.ts',
    variants: 4,
  },
  {
    id: 'empty-state',
    name: 'EmptyState',
    group: 'feedback',
    selectors: 'app-empty-state',
    source: 'empty-state/empty-state.ts',
    variants: 3,
  },
  {
    id: 'hint',
    name: 'Hint',
    group: 'feedback',
    selectors: 'app-hint',
    source: 'hint/hint.ts',
    variants: 2,
  },
  {
    id: 'status-block',
    name: 'StatusBlock',
    group: 'feedback',
    selectors: '[appStatusBlock]',
    source: 'status-block/status-block.ts',
    variants: 3,
  },
  {
    id: 'icon',
    name: 'Icon',
    group: 'feedback',
    selectors: 'app-icon',
    source: 'icon/icon.ts',
    variants: 44,
  },
  {
    id: 'entity-icon',
    name: 'EntityIcon',
    group: 'feedback',
    selectors: 'app-entity-icon',
    source: 'entity-icon/entity-icon.ts',
    variants: 5,
  },
  {
    id: 'input',
    name: 'input · FormField',
    group: 'fields',
    selectors: 'input, select, textarea + [formField]',
    source: 'field-group/field-group.ts',
    variants: 8,
  },
  {
    id: 'list-search',
    name: 'ListSearch',
    group: 'fields',
    selectors: 'app-list-search',
    source: 'list-search/list-search.ts',
    variants: 3,
  },
  {
    id: 'filter-menu',
    name: 'FilterMenu',
    group: 'fields',
    selectors: 'app-filter-menu',
    source: 'filter-menu/filter-menu.ts',
    variants: 3,
  },
  {
    id: 'filter-panel',
    name: 'FilterPanel',
    group: 'fields',
    selectors: 'ng-template[appFilterPanel]',
    source: 'filter-menu/filter-panel.ts',
    variants: 2,
  },
  {
    id: 'filter-choice',
    name: 'FilterChoice',
    group: 'fields',
    selectors: 'app-filter-choice',
    source: 'filter-choice/filter-choice.ts',
    variants: 3,
  },
  {
    id: 'date-range',
    name: 'DateRangeFilter',
    group: 'fields',
    selectors: 'app-date-range-filter',
    source: 'date-range-filter/date-range-filter.ts',
    variants: 3,
  },
  {
    id: 'object-picker',
    name: 'ObjectPicker',
    group: 'fields',
    selectors: 'app-object-picker',
    source: 'object-picker/object-picker.ts',
    variants: 3,
  },
  {
    id: 'field-group',
    name: 'FieldGroup',
    group: 'fields',
    selectors: 'fieldset[appFieldGroup]',
    source: 'field-group/field-group.ts',
    variants: 2,
  },
  {
    id: 'data-table',
    name: 'DataTable',
    group: 'data',
    selectors: '[appDataTable]',
    source: 'data-table/data-table.ts',
    variants: 2,
  },
  {
    id: 'table-sort',
    name: 'TableSort',
    group: 'data',
    selectors: 'button[appTableSort]',
    source: 'table-sort/table-sort.ts',
    variants: 3,
  },
  {
    id: 'table-export',
    name: 'TableExport',
    group: 'data',
    selectors: 'app-table-export',
    source: 'table-export/table-export.ts',
    variants: 3,
  },
  {
    id: 'filter-chip',
    name: 'FilterChip',
    group: 'data',
    selectors: 'button[appFilterChip]',
    source: 'filter-chip/filter-chip.ts',
    variants: 2,
  },
  {
    id: 'bulk-selection',
    name: 'BulkSelection',
    group: 'data',
    selectors: 'app-bulk-selection',
    source: 'bulk-selection/bulk-selection.ts',
    variants: 3,
  },
  {
    id: 'list-toolbar',
    name: 'ListToolbar',
    group: 'data',
    selectors: 'app-list-toolbar',
    source: 'list-toolbar/list-toolbar.ts',
    variants: 2,
  },
  {
    id: 'list-workspace',
    name: 'ListWorkspace',
    group: 'data',
    selectors: '[appListWorkspace]',
    source: 'list-toolbar/list-workspace.ts',
    variants: 1,
  },
  {
    id: 'search-highlight',
    name: 'SearchHighlight',
    group: 'data',
    selectors: '[appSearchHighlight]',
    source: 'search-highlight.ts',
    variants: 2,
  },
  {
    id: 'event-history',
    name: 'EventHistory',
    group: 'data',
    selectors: 'app-event-history',
    source: 'event-history/event-history.ts',
    variants: 2,
  },
  {
    id: 'localized-date',
    name: 'LocalizedDatePipe',
    group: 'data',
    selectors: 'localizedDate',
    source: 'localized-date/localized-date-pipe.ts',
    variants: 3,
  },
  {
    id: 'detail-row',
    name: 'DetailRow',
    group: 'data',
    selectors: 'p[appDetailRow]',
    source: 'detail-row/detail-row.ts',
    variants: 2,
  },
  {
    id: 'breadcrumbs',
    name: 'Breadcrumbs',
    group: 'navigation',
    selectors: 'app-breadcrumbs',
    source: 'breadcrumbs/breadcrumbs.ts',
    variants: 2,
  },
  {
    id: 'tabs',
    name: 'Tabs',
    group: 'navigation',
    selectors: 'app-tabs',
    source: 'tabs/tabs.ts',
    variants: 2,
  },
  {
    id: 'tab-layout',
    name: 'TabLayout · TabPanel · TabPanelOutlet',
    group: 'navigation',
    selectors: '[appTabLayout], ng-template[appTabPanel], app-tab-panel-outlet',
    source: 'tabs/tab-panel.ts',
    variants: 1,
  },
  {
    id: 'drawer',
    name: 'Drawer',
    group: 'navigation',
    selectors: 'app-drawer',
    source: 'drawer/drawer.ts',
    variants: 2,
  },
  {
    id: 'confirmation',
    name: 'Confirmation',
    group: 'navigation',
    selectors: 'Confirmation.request()',
    source: 'confirmation/confirmation.ts',
    variants: 2,
  },
  {
    id: 'result-navigation',
    name: 'ResultNavigation',
    group: 'navigation',
    selectors: 'app-result-navigation',
    source: 'result-navigation/result-navigation.ts',
    variants: 3,
  },
  {
    id: 'page-header',
    name: 'PageHeader',
    group: 'presentation',
    selectors: 'app-page-header',
    source: 'page-header/page-header.ts',
    variants: 2,
  },
  {
    id: 'outcome-panel',
    name: 'OutcomePanel',
    group: 'presentation',
    selectors: 'aside[appOutcomePanel]',
    source: 'outcome-panel/outcome-panel.ts',
    variants: 1,
  },
  {
    id: 'visual-sample',
    name: 'VisualSample',
    group: 'presentation',
    selectors: 'app-visual-sample',
    source: 'visual-sample/visual-sample.ts',
    variants: 1,
  },
  {
    id: 'process-timeline',
    name: 'ProcessTimeline',
    group: 'presentation',
    selectors: 'app-process-timeline',
    source: 'process-timeline/process-timeline.ts',
    variants: 2,
  },
  {
    id: 'concrete-examples',
    name: 'ConcreteExamples',
    group: 'presentation',
    selectors: 'app-concrete-examples',
    source: 'concrete-examples/concrete-examples.ts',
    variants: 2,
  },
  {
    id: 'contact-actions',
    name: 'ContactActions',
    group: 'presentation',
    selectors: 'app-contact-actions',
    source: 'contact-actions/contact-actions.ts',
    variants: 2,
  },
  {
    id: 'site-header',
    name: 'SiteHeader',
    group: 'presentation',
    selectors: 'app-site-header',
    source: 'site-header/site-header.ts',
    variants: 1,
  },
  {
    id: 'mobile-navigation',
    name: 'MobileNavigation',
    group: 'navigation',
    selectors: 'app-mobile-navigation',
    source: 'mobile-navigation/mobile-navigation.ts',
    variants: 1,
  },
  {
    id: 'site-footer',
    name: 'SiteFooter',
    group: 'presentation',
    selectors: 'app-site-footer',
    source: 'site-footer/site-footer.ts',
    variants: 2,
  },
  {
    id: 'language-selector',
    name: 'LanguageSelector',
    group: 'presentation',
    selectors: 'app-language-selector',
    source: 'language-selector/language-selector.ts',
    variants: 2,
  },
  {
    id: 'theme-toggle',
    name: 'ThemeToggle',
    group: 'presentation',
    selectors: 'app-theme-toggle',
    source: 'theme-toggle/theme-toggle.ts',
    variants: 1,
  },
  {
    id: 'new-label',
    name: 'NewLabel',
    group: 'presentation',
    selectors: 'app-new-label',
    source: 'new-label/new-label.ts',
    variants: 1,
  },
  {
    id: 'back-office-header',
    name: 'BackOfficeHeader',
    group: 'navigation',
    selectors: 'app-back-office-header',
    source: 'back-office-header/back-office-header.ts',
    variants: 1,
  },
  {
    id: 'back-office-nav',
    name: 'BackOfficeNav',
    group: 'navigation',
    selectors: 'app-back-office-nav',
    source: 'back-office-nav/back-office-nav.ts',
    variants: 1,
  },
  {
    id: 'global-search',
    name: 'GlobalSearch',
    group: 'fields',
    selectors: 'app-global-search',
    source: 'global-search/global-search.ts',
    variants: 1,
  },
  {
    id: 'document-issues',
    name: 'DocumentIssues',
    group: 'feedback',
    selectors: 'app-document-issues',
    source: 'document-issues/document-issues.ts',
    variants: 2,
  },
  {
    id: 'mermaid-diagrams',
    name: 'MermaidDiagrams',
    group: 'presentation',
    selectors: '[appMermaidDiagrams]',
    source: 'mermaid-diagrams.ts',
    variants: 2,
  },
  {
    id: 'copy-notice',
    name: 'CopyNotice',
    group: 'feedback',
    selectors: 'app-copy-notice',
    source: 'copy-notice/copy-notice.ts',
    variants: 1,
  },
  {
    id: 'workflows',
    name: 'DesignWorkspace',
    group: 'compositions',
    selectors: 'app-design-workspace',
    source: '../../pages/design/design-workspace/design-workspace.ts',
    variants: 5,
  },
];

export const referenceGroups: readonly ReferenceGroup[] = [
  'actions',
  'feedback',
  'fields',
  'data',
  'navigation',
  'presentation',
  'compositions',
];
