API_TOKEN_HMAC_KEY: ENC[AES256_GCM,data:DBws1uYQHbnaXrKGYyHDfIezedCBDfkknVtroq3bIioMNQ7dbqnAm4dL6Q==,iv:ivlUbZ4jqt0Jvf2CwEvYGr8NgOMx5oZt/n7CPtZ0snI=,tag:5ouXJusm4qoJhZPNRjI7zQ==,type:str]
BOOTSTRAP_PASSWORD_SCRYPT: ENC[AES256_GCM,data:zagFADsucCfWQsHX6j0XduHpLS9//kMnl08Nq85mzhR5sHsWRYWf6CfZBGeDZWiYNPPMtshMwlN12VdwFyNrqlXuOz9Ww9GF9vDtTMj4hNNs3Ec58Fs2C7OtsLSOSYc99zrTdHI98xWT+pB18nDCrSuvUDIdIZAj7v9V+AgX,iv:ET2DseQv21U8njduGDJcyeFO6297r8v7/+0Ea1a3tNQ=,tag:5P3waDzXIdq+AONcsJHXJw==,type:str]
PASETO_SECRET_KEY: ENC[AES256_GCM,data:QbTCzjXMEmtWGQ3z8FZsGHy6ZRxqbHoLenI7uvB00huJFIJwctwxG1xOno/wexbG87ZKsUPrx1G+Vhuqr6x0M4jg1b1eu7uO+qSp25G1WRgonOyyvgjT2Eg+8qwVBnxA,iv:CPExqZPz3ro/FjfIYXsRS9YsfbTaRm73MRY/xH20aXA=,tag:7LWg+2CLmRsxn/4jFcVMTg==,type:str]
QUOTE_LINK_HMAC_KEY: ENC[AES256_GCM,data:7vmbm53FDf6tl2EI/Yp+lS6Cd5w4Q/dAE0gAscRWOYKv1lRILGooejjk9g==,iv:4FA5hVsmqylzsMOerx9IyQ9esU+fhL3Vw1xmdUTP4F0=,tag:WuX5EBbTjrYdepSccregnA==,type:str]
REFRESH_HMAC_KEY: ENC[AES256_GCM,data:faU0PYm3hiILCOlsfe2drXFrT1TLaF5/NWPE5b2+YQIASr6eRe9IWSXTnA==,iv:xPzWwQ+/GK/E566nw9CbS19uP74jPfp8Jr6BkEC1RkA=,tag:/bS7US5jOusPu78kzaMleA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b0pXeTdSOWFsUVV0ejR1
            cW5WU3UwVElGV1FsWTBiMy9FWGZLaFY2Ykd3ClpPVlR0WGgwWDVIc2dkY1Q1dTlv
            WjdLYjN4YW1rMzdKZGdHa3J3TUthYUkKLS0tIHNNdytyT2VIQXNiUXVwQTRLL0xJ
            MU5DZlZTU3d2blhRSzBxVUtxTFNOaVUKO8i44YzObl3X2/w2blv1HZ3RiffCx/v+
            QW8ty/eOWZwarPAZinesxxutgENwv6u4+CdY6vcXZl3F0GfhxKECGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t6n6jyy0uwh6px3tl65pjrd5m0f79dv5xja2dcpq2gpvq0jcsyjs6j40fe
    lastmodified: "2026-08-23T16:14:19Z"
    mac: ENC[AES256_GCM,data:iCt0W080kgMMrh/kdOOHV9Wdm2L/H2E8wTXkXBMkGMwFwfAcH/jDdOyKfPb3yGFPiysPGo1t3b5WNfTS4/yfCCAbe4nbkhBVXox+rac2Jm9CFl7LsSQoIdKfxj9zNri6yotJ75ye1K+6Sw4Sx3o3m3/tU4kcbOZFnQCqTPL4Eps=,iv:Dg01hSFe4kLVjx9mDfeBktomDk93ZrWVCeNQuPPjfJc=,tag:sLZ7iwR/8epM7IrVSEDOQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
