API_TOKEN_HMAC_KEY: ENC[AES256_GCM,data:06RNA/5TtDhi1VWODAZUDavHPU/1bFYSarlPrxadeBvHp5LEKv1nTS/CXw==,iv:YwCGVIT2lFBnPm+CAVSmHD/PBXSgFUmwvrLYKAD1R7E=,tag:5g9JxxkoyGiNxe9ieJc+Fg==,type:str]
BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:qNwSm+4yBzWDRcGuwssZ2kujTTWS8cmI31OkFbO3RHU=,iv:L7QOv6kyNSqXTO1QuN6q8+ra46YBqrhGA7BjrBO6fF0=,tag:76ubFH1Ur0mV4GykVKHk6Q==,type:str]
BOOTSTRAP_PASSWORD_SCRYPT: ENC[AES256_GCM,data:tEGYg2P38ivskZ1PfvmvtDREc1lBqcI+XrjMgkYkZEAbKqM0nMb9i6jOBS7xBgR8obpoe4lUVwcU71LoUQQxETVoVb5W07uUVKc48CR7QdS272uGleksCTL0ZHKdna32wpDNxRf3gvtMUSuxgBQJFyIfiDUBoLvGrmWM2kSo,iv:CmfDxj617SXTwnceLxXhTiEKXy34ek65VRTwutENm+A=,tag:qGxPFnY6aRPN+KDyJ5P8uw==,type:str]
PASETO_SECRET_KEY: ENC[AES256_GCM,data:/7jg52A7HPg/eyqSPwxkfDkMOeH5FAWgB4GZM/lLi26DErJWQbYbQNQFHPXAqfg3vlL7i9cweVZAqx6SIRTaxThVGJ/o390k5oivEb+gHdVxldN9il8VkgAtbgcmIznK,iv:xHrlHBgCuVb8YMVGJa6zg3FQbtIe+ncyM7+27Onby38=,tag:gS5roeqBTLvT/5r2y+Ib+A==,type:str]
QUOTE_LINK_HMAC_KEY: ENC[AES256_GCM,data:WBbbPTGCOvTuJpganZSlIve9GNAwPMQWBIqsEjldKAH/e7rnaYqu0DBSsQ==,iv:CqYE3qbPxIV0lnQFYilZDce5cEdPG59lKwXr+ej/2a8=,tag:cEgINgjaXScUBcL6qRoCFQ==,type:str]
REFRESH_HMAC_KEY: ENC[AES256_GCM,data:cC9HSMYtELLG5e5Qa22XoQi0fMmZJza+sj7Y5QWUNHrXpk2npUbqMNFT9g==,iv:DOCv+Er9q3BnC0F5XzSCyK7KiCB0THOanKokmHz918M=,tag:7D1xTuuRC4ZipxQd2eyY1A==,type:str]
DEMO_PASSWORD: ENC[AES256_GCM,data:/qmwxAIV3apVSOrRsAKBTNpE4BFkOtmsPj6yS6BbwsQ=,iv:OwAKQBzsm7hQN6Pl031PRQ4+rfyxQrqQlMVKVtltDq8=,tag:XA3Rk8J0iWq1lXLlnqtiVA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TDYvbHphekd1QzB1ZGRQ
        TzZ3S0F6M3Zvd0hNQU9JNUI0dUtPSmRDRFhvCjJYdHU3ODlEWkV3VkZSTHlmRlBh
        cEJEY1l2bkxIcTYwRklMcDlva0IwK1kKLS0tIHpJUTY1dC81VzBlYUcwWW0yWTgw
        Ykx1NFJsNkcvR0NhUytPL2VzUGhXSEkKjc9Sdx4tjrdlRwATZ2b6ebseA51P+s76
        MNLdBvkFVCp5gEHpoarLijbqantpOuXAdh7g4gtCqEzakB9kymMIqw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1t6n6jyy0uwh6px3tl65pjrd5m0f79dv5xja2dcpq2gpvq0jcsyjs6j40fe
  lastmodified: "2026-09-13T06:44:30Z"
  mac: ENC[AES256_GCM,data:QPlETHivuHuXnlnTjf7enTjnoIR6/jfw6jVaZ0YE2mKGGdwbWUwL5jTnJtxdeAlwQ3YAHMoAc0SK9BhJn2DT5zxin8L5lAmWCKRRoPdZeISJG1h5MFbDVA3dUe4puNmSfO8MRO1YKpoYK9hbSSGflvRPCk6OB/hSaSucpMTsaL0=,iv:ajNEm/d+6uAK1Lrv0wg6oEgxK0HvYQS4Vyt5E6AUq1g=,tag:Sywgk7alzi1jlThzQOxs0A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
