name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  platform:
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: sachahjkl/deployment-actions/.github/workflows/application-ci.yml@v6.0.3
    with:
      deployment-environment: staging

  backoffice-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: sachahjkl/deployment-actions/.github/actions/setup-nix@6f561705d9b1e662bb7dbd0852b1f8368e3ba3b4
      - run: nix flake check "path:$PWD/backoffice" --print-build-logs --max-jobs 2
